### ISSUE TITLE
Connect to Owntracks server?

### ISSUE THREAD

**Issue by dofl** [jhotmann/pinpoint#35]
I've got pinpoint running in a docker and I'm able to get to the website and register a user
But I cannot register a device (although I can create a group). I'm guessing there is something missing to connect to the MQTT server used by Owntracks?

How does the app communicate with this MQTT server? Or in my case Owntracks HTTP mode? I clearly don't understand where to position pinpoint between Owntracks in order to get it right.

Some logs to give some insight in my usage.

**docker.compose.yaml**
```
services:
  otrecorder:
    image: owntracks/recorder
    container_name: owntracks
    ports:
      - 8083:8083 
    volumes:
      - ./config:/config
      - ./store:/store
    restart: unless-stopped

  pinpoint:
    image: jhot/pinpoint:latest
    container_name: owntracks-pinpoint
    restart: unless-stopped
    ports:
      - 8084:8000
    volumes:
      - ./pinpoint:/app/data
    environment:
      - HTTP_HOST=https://owntracks.domain.name
      - ADMIN_PASSWORD=password
      - JWT_SECRET=secret
```

**docker logs (removed lines where javascript and style is loaded)**
```
owntracks       | ot-recorder[7]: version 0.9.0 starting with STORAGEDIR=/store
owntracks       | ot-recorder[7]: Not using MQTT: disabled by port=0
owntracks       | ot-recorder[7]: HTTP listener started on 0.0.0.0:8083
owntracks       | ot-recorder[7]: Using storage at /store with precision 7
owntracks-pinpoint | 
owntracks-pinpoint | > pinpoint@1.0.0 start
owntracks-pinpoint | > forever ./bin/www
owntracks-pinpoint | 
owntracks-pinpoint | warn:    --minUptime not set. Defaulting to: 1000ms
owntracks-pinpoint | warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
owntracks-pinpoint | (node:19) Warning: Accessing non-existent property padLevels of module exports inside circular dependency
owntracks-pinpoint | (Use node --trace-warnings ... to show where the warning was created)
owntracks-pinpoint | (node:19) Warning: Accessing non-existent property padLevels of module exports inside circular dependency
owntracks-pinpoint | Card cache will be cleared at Tue May 31 2022 00:00:00 GMT+0000
owntracks-pinpoint | Express server listening on port 8000
owntracks-pinpoint | GET / 200 98.008 ms - 2524
owntracks-pinpoint | GET /login 200 15.056 ms - 3144
owntracks-pinpoint | POST /login 302 95.543 ms - 28
owntracks-pinpoint | GET /admin 200 232.080 ms - 3174
owntracks-pinpoint | GET /admin/generate-registration 200 53.791 ms - 433
owntracks-pinpoint | GET / 200 10.759 ms - 2624
owntracks-pinpoint | GET /register/3sFza882nd4WHMLR0eWh0JTFaGGOgTC0jh6pXWmu 200 35.203 ms - 3504
owntracks-pinpoint | POST /register/3sFza882nd4WHMLR0eWh0JTFaGGOgTC0jh6pXWmu 302 4107.066 ms - 28
owntracks-pinpoint | GET /login 200 12.063 ms - 3144
owntracks-pinpoint | GET /register/javascripts/json-enc.js 404 21.173 ms - 171
owntracks-pinpoint | GET /register/javascripts/htmx.min.js 404 26.552 ms - 171
owntracks-pinpoint | POST /login 302 4007.137 ms - 27
owntracks-pinpoint | GET /user 200 148.251 ms - 10134
owntracks-pinpoint | GET /user/add-device 200 33.421 ms - 1777
owntracks-pinpoint | GET /user/add-device 304 13.384 ms - -
owntracks-pinpoint | GET / 200 12.121 ms - 2524
```
